name = "exercise_generator"
version = "0.1.0"
description = "Test and stub file generator for the Exercism Gleam track"

[dependencies]
gleam_stdlib = "~> 0.26"
gleam_json = "~> 0.5"
simplifile = ">= 1.7.0 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
